# Generated by Django 3.2.7 on 2021-09-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('appetizer', 'appetizer'), ('entree', 'entree'), ('dessert', 'dessert')], max_length=100)),
            ],
            options={
                'verbose_name': 'food_item',
                'verbose_name_plural': 'food_items',
                'db_table': 'food_item',
            },
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('description', models.CharField(max_length=254)),
                ('image', models.ImageField(upload_to='restaurant')),
                ('phone', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
            ],
            options={
                'verbose_name': 'restaurant',
                'verbose_name_plural': 'restaurants',
                'db_table': 'restaurant',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='restaurant.restaurant')),
                ('food_items', models.ManyToManyField(to='restaurant.FoodItem')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'db_table': 'menu',
            },
        ),
    ]
