# Generated by Django 3.2.7 on 2021-09-21 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_restaurantimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantimage',
            name='restaurant',
        ),
        migrations.AlterField(
            model_name='restaurantimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
