# Generated by Django 3.2.7 on 2021-09-21 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210921_1531'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantimage',
            name='name',
        ),
    ]
