# Generated by Django 3.2.7 on 2021-09-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_remove_restaurantimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantimage',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurantimage',
            name='restaurant',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
