# Generated by Django 3.2.7 on 2021-09-22 01:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_alter_restaurantimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='restaurant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurant.restaurant'),
            preserve_default=False,
        ),
    ]
