# Generated by Django 3.2.7 on 2021-09-20 13:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_IP', models.GenericIPAddressField(null=True)),
                ('login_datetime', models.DateTimeField(auto_now=True)),
                ('login_username', models.CharField(max_length=40, null=True)),
                ('status', models.CharField(default='success', max_length=40, null=True)),
                ('user_agent_info', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Login Activity',
                'verbose_name_plural': 'Login Activities',
                'db_table': 'user_login_activity',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='exit', max_length=254, unique=True, validators=[django.core.validators.EmailValidator], verbose_name='user email address'),
            preserve_default=False,
        ),
    ]
