# Generated by Django 3.2.7 on 2021-09-20 13:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210920_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=254, validators=[django.core.validators.EmailValidator], verbose_name='user email address'),
        ),
    ]
