# Generated by Django 3.2.7 on 2021-09-21 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_types',
            field=models.IntegerField(choices=[(1, 'client'), (2, 'restaurant')], default=1),
        ),
    ]
